// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb_4A2XlJo-YEbfDVFuQoZBq5vBXL1v4Y',
    appId: '1:347861976641:web:9102fb371727942cb1e8c0',
    messagingSenderId: '347861976641',
    projectId: 'tinytasks-c3045',
    authDomain: 'tinytasks-c3045.firebaseapp.com',
    storageBucket: 'tinytasks-c3045.firebasestorage.app',
    measurementId: 'G-ZLFG6SN1QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjv2cw9zC1Hm3YCKNJ5jDMUoPblv1uB60',
    appId: '1:347861976641:android:3ab8294d2e2c007bb1e8c0',
    messagingSenderId: '347861976641',
    projectId: 'tinytasks-c3045',
    storageBucket: 'tinytasks-c3045.firebasestorage.app',
  );
}
